# Generated by Django 5.0.7 on 2024-07-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(
                default="profile_pics/blank_profile.png",
                upload_to="media/profile_pics/",
            ),
        ),
    ]
