# Generated by Django 5.0.7 on 2024-07-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_userprofile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(
                default="users/profile_pics/blank_profile.png",
                upload_to="users/profile_pics/",
            ),
        ),
    ]
