# Generated by Django 5.0.7 on 2024-07-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_userprofile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
