# Generated by Django 5.0.7 on 2024-07-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_address_userprofile_street_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
    ]
