# Generated by Django 5.0.7 on 2024-07-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_userprofile_subscription_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
