# Generated by Django 5.0.7 on 2024-07-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_userprofile_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
