# Generated by Django 5.0.7 on 2025-01-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_userprofile_subscription_duration_months'),
    ]

    operations = [
    ]
