# Generated by Django 5.0.7 on 2025-01-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_userprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
    ]
