# Generated by Django 5.0.7 on 2025-01-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_userprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_subscribed_to_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
