# Generated by Django 5.0.7 on 2025-01-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_userprofile_is_subscribed_to_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_subscribed_to_newsletter',
        ),
    ]
