# Generated by Django 5.0.7 on 2025-01-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_userprofile_is_subscribed_to_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_booked_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_booked_day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_booked_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
