# Generated by Django 5.0.7 on 2025-01-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_booking_user'),
        ('users', '0029_userprofile_last_booked_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_booked_class',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_booked_day',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_booked_time',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='booked_classes',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='classes.booking'),
        ),
    ]
