# Generated by Django 5.0.7 on 2025-01-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_booking_user_alter_classtime_fitness_class'),
        ('users', '0030_remove_userprofile_last_booked_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='booked_classes',
            field=models.ManyToManyField(blank=True, to='classes.booking'),
        ),
    ]
