# Generated by Django 5.0.7 on 2024-07-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0005_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classtime",
            name="time_range",
            field=models.CharField(max_length=11),
        ),
    ]
