# Generated by Django 5.0.7 on 2025-01-29 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='fitness_class',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Pilates', 'Pilates'), ('Spinning', 'Spinning'), ('Zumba', 'Zumba'), ('Crossfit', 'CrossFit'), ('Boxing', 'Boxing'), ('Hiit', 'HIIT (High-Intensity Interval Training)')], max_length=20),
        ),
    ]
