# Generated by Django 5.0.7 on 2025-01-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_booking_user_alter_classtime_fitness_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='fitness_class',
            field=models.CharField(choices=[('yoga', 'Yoga'), ('pilates', 'Pilates'), ('spinning', 'Spinning'), ('zumba', 'Zumba'), ('crossfit', 'CrossFit'), ('boxing', 'Boxing'), ('hiit', 'HIIT (High-Intensity Interval Training)')], max_length=20),
        ),
    ]
