# Generated by Django 5.0.7 on 2025-01-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_alter_classtime_fitness_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='class_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='time_range',
            field=models.CharField(max_length=20),
        ),
    ]
