# Generated by Django 5.0.7 on 2024-07-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='image',
            field=models.ImageField(upload_to='plans/'),
        ),
    ]
