# Generated by Django 5.0.7 on 2024-07-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionplan_binding_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='binding_period',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='binding_time',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
