# Generated by Django 5.0.7 on 2024-07-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_subscriptionplan_binding_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='binding_time',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
