# Generated by Django 5.0.7 on 2024-07-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('product_id', models.CharField(max_length=50)),
                ('listing_id', models.CharField(max_length=50)),
                ('highlights', models.TextField()),
                ('availability', models.CharField(max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('avg_rating', models.FloatField()),
            ],
        ),
    ]
